// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icwqzsfebdyrfseslswn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljd3F6c2ZlYmR5cmZzZXNsc3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTUzMzksImV4cCI6MjA2NTQ3MTMzOX0.bnBIlJnA16ffQX5UtVHzVZ4kdofa6d4q0GQ3AbWhPrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);